### ISSUE TITLE
[Feature] How to get involved features

### ISSUE THREAD

**Issue by siyafrica** [afrimapr/afrimapr.website#17]
**Is your feature request related to a problem? Please describe.**
I clicked on "How to get involved" and I have a list of suggestions I'd like to submit.

**Describe the solution you'd like**
The list of resources and links would work better if it were divided into:
Links for getting in contact with Afrimpr - via Twitter and Google Groups [these links should also open in a new tab so that the user isn't taken away from the site]
Links for contributing code - to the Github repos  [these links should also open in a new tab so that the user isn't taken away from the site]
Links for learning - links for anyone who wants to up-skill in order to contribute to Afrimapr [this link can link to the learning materials page]
I think a FAQ page (or a paragraph) on explaining the kind of help you are looking for and that can offer would be a good addition too.

**Comment by anelda** [comment]
Hi @siyafrica, thanks for your excellent suggestions. I will consider how to implement this today and suggest something later. Will appreciate it hugely if you can give more input on the new structure when you have time. I'll paste a link here in this issue so that you'll be notified when it is ready for comment.

**Comment by anelda** [comment]
@siyafrica @andysouth I added a paragraph at the top of the page to specify the kind of help we're looking for, but this will have to be updated as the project evolve. 

I also changed all the links so that they will now open in a new tab.

And I added Andy's email address.

It's a start. Please let me know if you'd like me to add/change/remove anything?

**Comment by andysouth** [comment]
Thanks @siyafrica for your contribution and thanks for the implementation @anelda 
Good improvements, further input welcome :-)

**Comment by siyafrica** [comment]
Thank you @anelda for allowing me to contribute. The updates look great and work well.
